# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            neil weisenfeld
tagline:          
description:      "I've been working at the intersection of computer science and biological research for more than a decade.  Here's what I'm thinking about these days."
url:              http://www.neilweisenfeld.com

author:
  name:           'Neil Weisenfeld'
  url:            https://twitter.com/weisen

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           
